### ISSUE TITLE
[BUG]AttributeError: module 'torch' has no attribute 'Any'

### ISSUE THREAD

**Issue by noforit** [Vahe1994/AQLM#136]
Is there a need to restrict the PyTorch version to be lower than a certain version when running the aqlm library? I'm encountering the following errors when using torch-2.5.0.

```
processing eval data by layer:   0%|          | 0/32 [00:00<?, ?it/s]

calc outs after quantization:   0%|          | 0/83 [00:00<?, ?it/s][A/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference_kernels/cuda_kernel.py:20: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat")
/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference_kernels/cuda_kernel.py:33: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat_dequant")
/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference_kernels/cuda_kernel.py:48: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat_dequant_transposed")
/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference_kernels/cuda_kernel.py:62: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat")
/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference_kernels/cuda_kernel.py:75: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat_dequant")
/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference_kernels/cuda_kernel.py:88: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat_dequant_transposed")


                                                                    [A
processing eval data by layer:   0%|          | 0/32 [00:54<?, ?it/s]
Traceback (most recent call last):
  File "/home/jishiyu/quantization/AQLM_origin/main.py", line 919, in <module>
    main()
  File "/home/jishiyu/quantization/AQLM_origin/main.py", line 911, in main
    perplexity_eval(model, testloader, args)
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/quantization/AQLM_origin/main.py", line 392, in perplexity_eval
    update_outs(layer, inps[0], outs[0], compute_mse=False, **forward_args)
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/quantization/AQLM_origin/main.py", line 542, in update_outs
    outs_batch = layer(inps_tensor[j].to(device).unsqueeze(0), **forward_args)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 741, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
                                                          ^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 636, in forward
    query_states = self.q_proj(hidden_states)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference.py", line 70, in forward
    self.prepare_matmul_op(input)
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference.py", line 85, in prepare_matmul_op
    self.gemv_op = _get_autograd_matmul_op(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference.py", line 99, in _get_autograd_matmul_op
    class _QuantizedMatmul(torch.autograd.Function):
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference.py", line 102, in _QuantizedMatmul
    ctx: torch.Any,
         ^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/__init__.py", line 2563, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'Any'

```

**Comment by noforit** [comment]
```
processing eval data by layer:   0%|          | 0/32 [00:00<?, ?it/s]

calc outs after quantization:   0%|          | 0/83 [00:00<?, ?it/s][A/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference_kernels/cuda_kernel.py:20: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat")
/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference_kernels/cuda_kernel.py:33: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat_dequant")
/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference_kernels/cuda_kernel.py:48: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat_dequant_transposed")
/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference_kernels/cuda_kernel.py:62: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat")
/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference_kernels/cuda_kernel.py:75: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat_dequant")
/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference_kernels/cuda_kernel.py:88: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat_dequant_transposed")


                                                                    [A
processing eval data by layer:   0%|          | 0/32 [00:54<?, ?it/s]
Traceback (most recent call last):
  File "/home/jishiyu/quantization/AQLM_origin/main.py", line 919, in <module>
    main()
  File "/home/jishiyu/quantization/AQLM_origin/main.py", line 911, in main
    perplexity_eval(model, testloader, args)
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/quantization/AQLM_origin/main.py", line 392, in perplexity_eval
    update_outs(layer, inps[0], outs[0], compute_mse=False, **forward_args)
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/quantization/AQLM_origin/main.py", line 542, in update_outs
    outs_batch = layer(inps_tensor[j].to(device).unsqueeze(0), **forward_args)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 741, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
                                                          ^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 636, in forward
    query_states = self.q_proj(hidden_states)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference.py", line 70, in forward
    self.prepare_matmul_op(input)
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference.py", line 85, in prepare_matmul_op
    self.gemv_op = _get_autograd_matmul_op(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference.py", line 99, in _get_autograd_matmul_op
    class _QuantizedMatmul(torch.autograd.Function):
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/aqlm/inference.py", line 102, in _QuantizedMatmul
    ctx: torch.Any,
         ^^^^^^^^^
  File "/home/jishiyu/miniconda3/envs/aqlm0/lib/python3.11/site-packages/torch/__init__.py", line 2563, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'Any'

```

**Comment by noforit** [comment]
> Hello, @noforit ! Try running this using torch==2.4.0. It should work.

Thanks a lot ！

**Comment by BenjaminBossan** [comment]
Will there be a fix for this to make it work with torch 2.5? This looks like an easy fix, just import `Any` from `typing` instead.
